### ISSUE TITLE
Texture/Samplers use incorrect register slots

### ISSUE THREAD

**Issue by NoelFB** [NoelFB/blah#16]
In D3D11 you can specify which registers textures/samplers get bound to, but the Material API (and in turn, what ends up getting rendered) assumes their order is their register, which is incorrect, especially since you can skip registers in HLSL. (Which can happen if, for example, the texture at register 0 is unused, and the HLSL compiler strips it out).

Should be a pretty trivial fix, just need to use the `D3D11_SHADER_INPUT_BIND_DESC` `BindPoint` variable and use that. Will need to refactor how Materials work a little bit, and make sure the behavior is the same in OpenGL. Will get to this sometime next week.

**Comment by RandyGaul** [comment]
Hey you’re probably messing with the d3d api directly for learning purposes, though I wanted to mention sokol_gfx.h since it wraps up a variety of backends. I use it in Cute Framework. It’s a lot easier to use due to good documentation compared to gl or d3d itself.

And it’s still quite good for learning purposes, as you can implement something via sokol_gfx and then follow the call stack to see how things are implemented for each backend. That’s how I’ve been learning about the 3D APIs. It’s pretty cool to trust the mapping from one backend to the other is correct, and see the differences after implementing something through sokol_gfx.

Edit: https://github.com/floooh/sokol/blob/master/sokol_gfx.h

**Comment by NoelFB** [comment]
Yeah! I've used it a little bit and it's great, I could see implementing it as another rendering backend that could be used instead of the ones I wrote. I do like learning this stuff which is the main reason I implemented my own :)

**Comment by NoelFB** [comment]
Fixed in https://github.com/NoelFB/blah/commit/410adbfe12e40c4e9d62d24dec28611117c5c029
